"""
Count unique token IDs across all patterns generated by `generator.py`

Usage:
    python tools/count_vocab.py --data-dir ./data/
"""

import argparse
import json
from pathlib import Path


def count_unique_tokens_for_folder(folder_path: Path) -> int:
    """Return the number of unique token IDs across all JSONL files in a folder."""
    unique_ids: set[int] = set()

    for jsonl_file in sorted(folder_path.glob("patterns.*.jsonl")):
        with open(jsonl_file) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                record = json.loads(line)
                unique_ids.update(record["input_ids"])

    return len(unique_ids)


def main(args):
    data_dir = Path(args.data_dir)

    results = {}

    # Iterate over each subfolder inside data/
    for subfolder in sorted(data_dir.iterdir()):
        if not subfolder.is_dir():
            continue
        # Skip hidden directories
        if subfolder.name.startswith("."):
            continue
        print(f"Processing {subfolder.name} ...")
        results[subfolder.name] = count_unique_tokens_for_folder(subfolder)

    # Pretty-print the results
    print("\n" + json.dumps(results, indent=2))

    # Save results to a JSON file inside the data directory
    out_path = data_dir / "unique_token_counts.json"
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nResults saved to {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--data-dir",
        type=str,
        required=True,
        help="Path to the data directory. (e.g., ./data/)",
    )

    args = parser.parse_args()
    main(args)
