"""Compute the Pareto frontier of epiplexity across model sizes.

This implements the full paper methodology from Finzi et al. (2026):
given single-model epiplexity reports (generated by epiplexity.py --json),
compute the lower convex hull of (compute, two-part code) across all runs.

Usage:
    # First, generate per-model reports:
    python tools/epiplexity.py \
        --model-params 100e6 --train-tokens 5.2e9 \
        --loss-curve model_100m_train.jsonl \
        --final-val-loss 2.90 \
        --json --output reports/model_100m.json

    python tools/epiplexity.py \
        --model-params 300e6 --train-tokens 5.2e9 \
        --loss-curve model_300m_train.jsonl \
        --final-val-loss 2.75 \
        --json --output reports/model_300m.json

    python tools/epiplexity.py \
        --model-params 670e6 --train-tokens 5.2e9 \
        --loss-curve model_670m_train.jsonl \
        --final-val-loss 2.70 \
        --json --output reports/model_670m.json

    # Then compute the Pareto frontier:
    python tools/epiplexity_pareto.py \
        --reports reports/model_*.json \
        --test-tokens 1e9 \
        --output pareto_report.md
"""

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path

LN2 = math.log(2)


@dataclass
class ParetoPoint:
    """A single (compute, code-length) point from one model at one checkpoint."""

    run_name: str
    model_params: int
    train_tokens: int
    total_compute_flops: float
    K_M_bits: float  # model description length S_T (total bits)
    K_X_given_M_bits: float  # data-given-model (bits)
    K_MX_bits: float  # total two-part code


def load_reports(patterns: list[str]) -> list[dict]:
    """Load JSON epiplexity reports from glob patterns or literal file paths."""
    import glob as glob_mod

    reports: list[dict] = []
    seen: set[str] = set()
    for pattern in patterns:
        # Try literal path first, then glob
        paths = [Path(pattern)] if Path(pattern).exists() else []
        if not paths:
            paths = [Path(p) for p in glob_mod.glob(pattern, recursive=True)]
        for path in sorted(paths):
            if str(path) in seen:
                continue
            seen.add(str(path))
            reports.append(json.loads(path.read_text()))
    if not reports:
        raise SystemExit("No reports found.  Did you generate them with --json?")
    return reports


def reports_to_points(reports: list[dict], test_tokens: float) -> list[ParetoPoint]:
    """Convert per-model epiplexity reports to two-part-code points.

    Following the paper (see https://arxiv.org/html/2601.03220v2):
        K(M)     = S_T_total       (prequential epiplexity, in bits)
        K(X|M)   = H_T * D_test    (time-bounded entropy x test tokens)
        K(M,X)   = K(M) + K(X|M)   (total two-part code)
        Compute  = 6·P·T + 2·P·D_test  (training + inference FLOPs)
    """
    points: list[ParetoPoint] = []
    for r in reports:
        p = r["model_params"]
        t = r["total_train_tokens"]

        # S_T total (bits), model description length
        K_M = r.get("S_bits", r["S_nats_total"] / LN2)

        # H_T per token (bits), time-bounded entropy
        H_per_token = r["H_bits_per_test_token"]

        K_X_given_M = H_per_token * test_tokens
        K_MX = K_M + K_X_given_M
        total_compute = 6.0 * p * t + 2.0 * p * test_tokens

        points.append(
            ParetoPoint(
                run_name=r.get("run_name", "?"),
                model_params=p,
                train_tokens=t,
                total_compute_flops=total_compute,
                K_M_bits=K_M,
                K_X_given_M_bits=K_X_given_M,
                K_MX_bits=K_MX,
            )
        )
    return points


def lower_convex_hull(points: list[ParetoPoint]) -> list[ParetoPoint]:
    """Compute the lower convex hull of (compute, K_MX) points.

    This is the Pareto frontier: for any given compute budget, no point
    below this hull achieves a smaller two-part code.  Models ON the hull
    are compute-optimal.
    """
    if len(points) < 2:
        return list(points)

    # Sort by x (compute)
    pts = sorted(points, key=lambda p: p.total_compute_flops)

    def cross(o: ParetoPoint, a: ParetoPoint, b: ParetoPoint) -> float:
        return (a.total_compute_flops - o.total_compute_flops) * (b.K_MX_bits - o.K_MX_bits) - (
            a.K_MX_bits - o.K_MX_bits
        ) * (b.total_compute_flops - o.total_compute_flops)

    hull: list[ParetoPoint] = []
    for p in pts:
        while len(hull) >= 2 and cross(hull[-2], hull[-1], p) <= 0:
            hull.pop()
        # Skip points that are strictly dominated in y
        if hull and p.K_MX_bits >= hull[-1].K_MX_bits:
            continue
        hull.append(p)

    return hull


def render_pareto_report(
    points: list[ParetoPoint], hull: list[ParetoPoint], test_tokens: float
) -> str:
    """Render the Pareto frontier as a Markdown report."""

    L: list[str] = []
    L.append("# Epiplexity Pareto Frontier")
    L.append("")
    L.append(f"Test tokens used for $K(X \\mid M)$: **{test_tokens:,.0f}**")
    L.append("")
    L.append("## All Models (two-part code)")
    L.append("")
    L.append(
        "| Run | Params | Train Tokens | $K(M)$ (bits) | $K(X\\mid M)$ (bits) | $K(M,X)$ (bits) | Compute (FLOPs) | On Frontier? |"
    )
    L.append("|---|---|---|---|---|---|---|---|")
    hull_runs = {p.run_name for p in hull}
    for pt in sorted(points, key=lambda p: p.total_compute_flops):
        on_frontier = "✓" if pt.run_name in hull_runs else ""
        L.append(
            f"| `{pt.run_name}` | {pt.model_params:,.0f} | {pt.train_tokens:,.0f} | "
            f"{pt.K_M_bits:.2e} | {pt.K_X_given_M_bits:.2e} | {pt.K_MX_bits:.2e} | "
            f"{pt.total_compute_flops:.2e} | {on_frontier} |"
        )
    L.append("")

    L.append("## Pareto Frontier (compute-optimal models)")
    L.append("")
    L.append(
        "| Run | Params | Compute (FLOPs) | $K(M,X)$ (bits) | $S_T$ = $K(M)$ (bits) | $S_T$ per 1B tok | $H_T$ per tok (bits) |"
    )
    L.append("|---|---|---|---|---|---|---|")
    for pt in hull:
        S_per_1B = pt.K_M_bits / (pt.train_tokens / 1e9) if pt.train_tokens > 0 else 0
        H_per_tok = pt.K_X_given_M_bits / test_tokens if test_tokens > 0 else 0
        L.append(
            f"| `{pt.run_name}` | {pt.model_params:,.0f} | {pt.total_compute_flops:.2e} | "
            f"{pt.K_MX_bits:.2e} | {pt.K_M_bits:.2e} | {S_per_1B:,.0f} | {H_per_tok:.4f} |"
        )
    L.append("")

    # Interpretation
    L.append("## Interpretation")
    L.append("")
    if len(hull) <= 1:
        L.append("Only one model on the frontier — run more model sizes to see the trade-off.")
    else:
        # S_T asymptote: use the largest model on the hull
        largest = hull[-1]
        S_inf = largest.K_M_bits
        L.append(
            f"- **Asymptotic $S_\\infty$** (largest model on frontier): **{S_inf:.2e} bits** "
            f"({S_inf / test_tokens:.4f} bits/test-token)"
        )
        L.append(
            f"- **$S_\\infty$ per 1B training tokens**: "
            f"**{S_inf / (largest.train_tokens / 1e9):,.0f} bits**"
        )
        L.append(
            "- The frontier shows how much more structure can be extracted by "
            "scaling compute — a flattening frontier means diminishing returns."
        )
        L.append(
            "- To convert $S_\\infty$ to the paper's epiplexity number, "
            "divide by the total training tokens of the largest model."
        )
    L.append("")

    return "\n".join(L)


def plot_frontier(
    points: list[ParetoPoint], hull: list[ParetoPoint], test_tokens: float, save_path: Path
) -> None:
    """Plot the 3-panel Pareto frontier figure and save to *save_path*.

    - Left:   K(M,X)  — total two-part code
    - Middle: K(M)    — epiplexity S_T
    - Right:  K(X|M)  — time-bounded entropy
    """
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.ticker as mticker

    hull_set = {p.run_name for p in hull}
    pts_sorted = sorted(points, key=lambda p: p.total_compute_flops)

    cmap = plt.cm.viridis
    unique_params = sorted({p.model_params for p in pts_sorted})
    norm = (
        matplotlib.colors.LogNorm(vmin=unique_params[0], vmax=unique_params[-1])
        if len(unique_params) > 1
        else matplotlib.colors.Normalize(vmin=unique_params[0], vmax=unique_params[0] + 1)
    )

    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(18, 5), sharex=True)

    panels = [
        (ax1, "K_MX_bits", r"$K(M,X)$  —  total two-part code (bits)"),
        (ax2, "K_M_bits", r"$K(M) = S_T$  —  epiplexity (bits)"),
        (ax3, "K_X_given_M_bits", r"$K(X \mid M) = H_T \cdot D_\mathrm{test}$  (bits)"),
    ]

    for ax, attr, ylabel in panels:
        # Individual model points (faint)
        for pt in pts_sorted:
            color = cmap(norm(pt.model_params))
            marker = "D" if pt.run_name in hull_set else "o"
            size = 80 if pt.run_name in hull_set else 40
            ax.scatter(
                pt.total_compute_flops,
                getattr(pt, attr),
                c=[color],
                s=size,
                marker=marker,
                edgecolors="black" if pt.run_name in hull_set else "none",
                linewidths=0.8 if pt.run_name in hull_set else 0,
                zorder=3 if pt.run_name in hull_set else 2,
                alpha=0.9 if pt.run_name in hull_set else 0.5,
            )

        # Pareto frontier line
        if len(hull) >= 2:
            hx = [p.total_compute_flops for p in hull]
            hy = [getattr(p, attr) for p in hull]
            ax.plot(hx, hy, "k-", linewidth=2, zorder=4, alpha=0.85)
            ax.plot(hx, hy, "ko", markersize=6, zorder=5)

        ax.set_xscale("log")
        ax.set_xlabel("Compute (FLOPs)")
        ax.set_ylabel(ylabel)
        ax.grid(True, alpha=0.3)

        # Scientific notation on y-axis
        ax.yaxis.set_major_formatter(mticker.ScalarFormatter(useMathText=True))
        ax.ticklabel_format(axis="y", style="sci", scilimits=(-2, 2))

    # Colour bar
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=[ax1, ax2, ax3], shrink=0.6, pad=0.02)
    cbar.set_label("Model parameters")

    # Legend for frontier vs non-frontier
    from matplotlib.lines import Line2D

    legend_elements = [
        Line2D(
            [0],
            [0],
            marker="D",
            color="w",
            markerfacecolor="gray",
            markersize=10,
            markeredgecolor="black",
            markeredgewidth=0.8,
            label="On frontier",
        ),
        Line2D(
            [0],
            [0],
            marker="o",
            color="w",
            markerfacecolor="gray",
            markersize=8,
            alpha=0.5,
            label="Dominated",
        ),
    ]
    fig.legend(
        handles=legend_elements,
        loc="lower center",
        ncol=2,
        frameon=True,
        bbox_to_anchor=(0.5, -0.06),
    )

    fig.suptitle(
        f"Epiplexity Pareto Frontier  —  $D_\\mathrm{{test}}$ = {test_tokens:,.0f} tokens",
        fontsize=13,
        y=1.01,
    )
    fig.subplots_adjust(left=0.06, right=0.94, top=0.90, bottom=0.15, wspace=0.28)
    fig.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--reports",
        "-r",
        nargs="+",
        required=True,
        help="Glob patterns or paths to JSON epiplexity reports (e.g. 'reports/*.json').",
    )
    parser.add_argument(
        "--test-tokens",
        "-D",
        type=float,
        default=1e9,
        help="Number of test tokens for K(X|M) computation "
        "(default: 1e9).  This is the amount of held-out data "
        "used for the two-part code — it sets the scale of "
        "K(X|M) relative to K(M).",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        help="Write report to FILE instead of stdout.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output the hull as JSON instead of Markdown.",
    )
    parser.add_argument(
        "--plot",
        "-p",
        nargs="?",
        const=True,
        default=None,
        help="Save a 3-panel Pareto frontier plot.  "
        "If a path is given (e.g. --plot frontier.png), "
        "save there; otherwise auto-derive from --output "
        "(report.md → report.png).",
    )

    args = parser.parse_args()

    reports = load_reports(args.reports)
    points = reports_to_points(reports, args.test_tokens)
    hull = lower_convex_hull(points)

    if args.json:
        hull_data = [
            {
                "run_name": pt.run_name,
                "model_params": pt.model_params,
                "train_tokens": pt.train_tokens,
                "total_compute_flops": pt.total_compute_flops,
                "K_M_bits": pt.K_M_bits,
                "K_X_given_M_bits": pt.K_X_given_M_bits,
                "K_MX_bits": pt.K_MX_bits,
                "S_T_per_1B_tokens": pt.K_M_bits / (pt.train_tokens / 1e9)
                if pt.train_tokens > 0
                else 0,
                "H_T_bits_per_test_token": pt.K_X_given_M_bits / args.test_tokens
                if args.test_tokens > 0
                else 0,
            }
            for pt in hull
        ]
        output = json.dumps(hull_data, indent=2)
    else:
        output = render_pareto_report(points, hull, args.test_tokens)

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(output)
        print(f"Report written to {args.output}")
    else:
        print(output)

    # Plot
    if args.plot is not None:
        if isinstance(args.plot, str):
            plot_path = Path(args.plot)
        elif args.output:
            plot_path = args.output.with_suffix(".png")
        else:
            plot_path = Path("epiplexity_pareto.png")

        plot_frontier(points, hull, args.test_tokens, plot_path)
        print(f"Plot saved to {plot_path}")


if __name__ == "__main__":
    main()
